logging:
  level: INFO
  loggers:
    in.dailyhunt.personalization: DEBUG

server:
  rootPath: /*

# turning this true will scrap the data on server startup based on scrapper-config.yml
scrappingEnabledOnStartup: false